apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: managed-pipeline
  namespace: managed-releng
spec:
  applications:
    - demo
  origin: dev-release
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/seanconroy2021/sc-konflux-demos.git
        - name: revision
          value: main
        - name: pathInRepo
          value: RELEASE-1384/pipelines/managed-pipeline.yaml
    serviceAccountName: release-service-account
    taskRunSpecs:
      - pipelineTaskName: collect-data
        computeResources:
          limits:
            cpu: "600m"
            memory: "540Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
  policy: mvp-policy
