---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extended-release-access
rules:
- apiGroups: ["appstudio.redhat.com"]
  resources: ["releases", "releases/status", "releaseplans","releaseplanadmissions"]
  verbs: ["get"]
- apiGroups: ["appstudio.redhat.com"]
  resources: ["releases/status"]
  verbs: ["patch"]
- apiGroups: ["appstudio.redhat.com"]
  resources: ["internalrequests"]
  verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector-service-extended-access
subjects:
- kind: ServiceAccount
  name: collector-service
  namespace: user-ns2
- kind: ServiceAccount
  name: collector-service
  namespace: managed-ns2
roleRef:
  kind: ClusterRole
  name: extended-release-access
  apiGroup: rbac.authorization.k8s.io