---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-service-account
  namespace: managed-releng
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-pipeline-cr-test
  namespace: managed-releng
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
- kind: ServiceAccount
  name: release-service-account
  namespace: managed-releng
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-service-account
  namespace: dev-release
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-pipeline-cr-test
  namespace: dev-release
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
- kind: ServiceAccount
  name: release-service-account
  namespace: dev-release